# Generated by Django 3.0.6 on 2020-06-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200603_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('', 'Default')], max_length=200),
        ),
    ]
